apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: asia-clusters
  namespace: openshift-gitops
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
      - key: country
        operator: In
        values:
          - "china"
          - "thailand"
