# This is for the local ARGO on the Hub
---
apiVersion: apps.open-cluster-management.io/v1alpha1
kind: GitOpsCluster
metadata:
  name: argo-asia-cluster
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: asia-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: asia-cluster
    namespace: openshift-gitops

# This is the ManagedClusterSetBinding to the openshift-gitops namespace
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
metadata:
  name: asia-cluster
  namespace: openshift-gitops
spec:
  clusterSet: asia-cluster

#This is the placement resource for targeting Managed Clusters for
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: asia-cluster
  namespace: openshift-gitops
spec:
  #numberOfClusters: 6
  clusterSets:
  - asia-cluster
  

---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSet
metadata:
  name: asia-cluster
spec: {}

