apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etherpad-argo
  namespace: etherpad
spec:
  destination:
    name: local-cluster
    namespace: etherpad
    server: ''
  source:
    path: resources/etherpad
    repoURL: 'https://github.com/wdrdres3qew5ts21/redhat-advance-cluster-management.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
