apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: asia-clusters
  namespace: rhacm-policies
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
      - key: country
        operator: In
        values:
          # - "thailand"
          - "china"