apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-limitmemory
  namespace: rhacm-policies
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-limitrange
        spec:
          severity: medium
          namespaceSelector:
            exclude:
            - kube-*
            - openshift-*
            - openshift
            - open-cluster*
            - default
            - multicluster-endpoint
            include:
            - 'etherpad'
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: default-limit-range
                spec:
                  limits:
                  # - type: Container
                  #   default:
                  #     cpu: 50m
                  #     memory: 256Mi
                  #   defaultRequest:
                  #     cpu: 50m
                  #     memory: 256Mi
                  #   max:
                  #     cpu: 2
                  #     memory: 256Mi
                  - type: Pod
                    max:
                      cpu: 200m
                      memory: 700Mi
